In [1]:
import pandas as pd

In [2]:
apt_rent_19=pd.read_excel("/Users/kang/Pandas/Real/apt_rent_2019.xlsx")
apt_rent_18=pd.read_excel("/Users/kang/Pandas/Real/apt_rent_2018.xlsx")
apt_rent_17=pd.read_excel("/Users/kang/Pandas/Real/apt_rent_2017.xlsx")
apt_rent_16=pd.read_excel("/Users/kang/Pandas/Real/apt_rent_2016.xlsx")
apt_rent_15=pd.read_excel("/Users/kang/Pandas/Real/apt_rent_2015.xlsx")
apt_rent_14=pd.read_excel("/Users/kang/Pandas/Real/apt_rent_2014.xlsx")
apt_rent_13=pd.read_excel("/Users/kang/Pandas/Real/apt_rent_2013.xlsx")
apt_rent_12=pd.read_excel("/Users/kang/Pandas/Real/apt_rent_2012.xlsx")
apt_rent_11=pd.read_excel("/Users/kang/Pandas/Real/apt_rent_2011.xlsx")
apt_rent_10=pd.read_excel("/Users/kang/Pandas/Real/apt_rent_2010.xlsx")

In [17]:
apt_rent_2010_2019=pd.concat([apt_rent_19,apt_rent_18,apt_rent_17,apt_rent_16,apt_rent_15,apt_rent_14,apt_rent_13,apt_rent_12,apt_rent_11,apt_rent_10])

In [18]:
apt_rent_2010_2019.columns=['citytownvillage','zipcode','zipcode_main','zipcode_sub','name','category','size','yymm','dd','deposit','monthlyrent','floor','year_built','address']

In [19]:
apt_rent_2010_2019

,citytownvillage,zipcode,zipcode_main,zipcode_sub,name,category,size,yymm,dd,deposit,monthlyrent,floor,year_built,address
0,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),전세,77.75,201908,24,"50,000",0,9.0,1988,언주로 103
1,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),전세,77.75,201908,31,"48,000",0,1.0,1988,언주로 103
2,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),전세,77.75,201912,10,"55,000",0,8.0,1988,언주로 103
3,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),전세,77.75,201912,21,"65,000",0,2.0,1988,언주로 103
4,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),전세,77.75,202002,5,"53,000",0,8.0,1988,언주로 103
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92309,서울특별시 중랑구 중화동,274-76,274,76,한영(103),전세,50.29,201103,17,"10,000",0,5.0,2003,동일로144길 74
92310,서울특별시 중랑구 중화동,274-77,274,77,한영(104),전세,67.57,201101,21,"13,000",0,4.0,2003,동일로144길 74
92311,서울특별시 중랑구 중화동,11,11,0,현대휴앤미,전세,82.97,201104,10,"16,500",0,7.0,2007,봉화산로27가길 23
92312,서울특별시 중랑구 중화동,11,11,0,현대휴앤미,전세,100.20,201107,28,"16,000",0,6.0,2007,봉화산로27가길 23
92313,서울특별시 중랑구 중화동,11-7,11,7,현대휴앤미(102동),전세,67.36,201107,15,"19,000",0,6.0,2007,봉화산로27가길 19

In [20]:
apt_rent_2010_2019['citytownvillage']=apt_rent_2010_2019['citytownvillage'].astype(str)
apt_rent_2010_2019['name']=apt_rent_2010_2019['name'].astype(str)
apt_rent_2010_2019['deposit']=apt_rent_2010_2019['deposit'].astype(str).str.replace(',','')
apt_rent_2010_2019['monthlyrent']=apt_rent_2010_2019['monthlyrent'].astype(str).str.replace(',','')

In [23]:

apt_rent_2010_2019['deposit']=apt_rent_2010_2019['deposit'].astype(int)
apt_rent_2010_2019['monthlyrent']=apt_rent_2010_2019['monthlyrent'].astype(int)
apt_rent_2010_2019['city']=apt_rent_2010_2019['citytownvillage'].str.split(' ').str[0]
apt_rent_2010_2019['town']=apt_rent_2010_2019['citytownvillage'].str.split(' ').str[1]
apt_rent_2010_2019['village']=apt_rent_2010_2019['citytownvillage'].str.split(' ').str[2]
apt_rent_2010_2019['yy']=apt_rent_2010_2019['yymm'].astype(str).str.slice(0,4)
apt_rent_2010_2019['mm']=apt_rent_2010_2019['yymm'].astype(str).str.slice(4,6)
apt_rent_2010_2019['yy']=apt_rent_2010_2019['yy'].astype(int)
apt_rent_2010_2019['mm']=apt_rent_2010_2019['mm'].astype(int)

In [24]:
apt_rent_2010_2019

,citytownvillage,zipcode,zipcode_main,zipcode_sub,name,category,size,yymm,dd,deposit,monthlyrent,floor,year_built,address,city,town,village,yy,mm
0,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),전세,77.75,201908,24,50000,0,9.0,1988,언주로 103,서울특별시,강남구,개포동,2019,8
1,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),전세,77.75,201908,31,48000,0,1.0,1988,언주로 103,서울특별시,강남구,개포동,2019,8
2,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),전세,77.75,201912,10,55000,0,8.0,1988,언주로 103,서울특별시,강남구,개포동,2019,12
3,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),전세,77.75,201912,21,65000,0,2.0,1988,언주로 103,서울특별시,강남구,개포동,2019,12
4,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),전세,77.75,202002,5,53000,0,8.0,1988,언주로 103,서울특별시,강남구,개포동,2020,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92309,서울특별시 중랑구 중화동,274-76,274,76,한영(103),전세,50.29,201103,17,10000,0,5.0,2003,동일로144길 74,서울특별시,중랑구,중화동,2011,3
92310,서울특별시 중랑구 중화동,274-77,274,77,한영(104),전세,67.57,201101,21,13000,0,4.0,2003,동일로144길 74,서울특별시,중랑구,중화동,2011,1
92311,서울특별시 중랑구 중화동,11,11,0,현대휴앤미,전세,82.97,201104,10,16500,0,7.0,2007,봉화산로27가길 23,서울특별시,중랑구,중화동,2011,4
92312,서울특별시 중랑구 중화동,11,11,0,현대휴앤미,전세,100.20,201107,28,16000,0,6.0,2007,봉화산로27가길 23,서울특별시,중랑구,중화동,2011,7
92313,서울특별시 중랑구 중화동,11-7,11,7,현대휴앤미(102동),전세,67.36,201107,15,19000,0,6.0,2007,봉화산로27가길 19,서울특별시,중랑구,중화동,2011,7

In [25]:
apt_rent_2010_2019.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1478880 entries, 0 to 92313
Data columns (total 19 columns):
 #   Column           Non-Null Count    Dtype
---  ------           --------------    -----
 0   citytownvillage  1478880 non-null  object
 1   zipcode          1477659 non-null  object
 2   zipcode_main     1478880 non-null  int64
 3   zipcode_sub      1478880 non-null  int64
 4   name             1478880 non-null  object
 5   category         1478880 non-null  object
 6   size             1478849 non-null  float64
 7   yymm             1478880 non-null  int64
 8   dd               1478880 non-null  int64
 9   deposit          1478880 non-null  int64
 10  monthlyrent      1478880 non-null  int64
 11  floor            1478849 non-null  float64
 12  year_built       1478880 non-null  int64
 13  address          1478880 non-null  object
 14  city             1478880 non-null  object
 15  town             1478880 non-null  object
 16  village          1478880 non-null  object
 17  yy               1478880 non-null  int64
 18  mm               1478880 non-null  int64
dtypes: float64(2), int64(9), object(8)
memory usage: 225.7+ MB

In [26]:
del apt_rent_2010_2019['citytownvillage']
del apt_rent_2010_2019['yymm']
del apt_rent_2010_2019['zipcode_main']
del apt_rent_2010_2019['zipcode_sub']

In [27]:
neworder = ['city','town','village','name', 'category','size','deposit','monthlyrent','floor','year_built','yy','mm','dd','zipcode','address']
apt_rent_2010_2019=apt_rent_2010_2019.reindex(columns=neworder)

In [33]:
apt_rent_2010_2019['age']=2020-apt_rent_2010_2019['year_built']

In [34]:
apt_rent_all1=apt_rent_2010_2019.loc[apt_rent_2010_2019['yy']<2015]
apt_rent_all2=apt_rent_2010_2019.loc[apt_rent_2010_2019['yy']>2014]

In [36]:
apt_rent_all2

,city,town,village,name,category,size,deposit,monthlyrent,floor,year_built,yy,mm,dd,zipcode,address,age
0,서울특별시,강남구,개포동,개포2차현대아파트(220),전세,77.75,50000,0,9.0,1988,2019,8,24,655-2,언주로 103,32
1,서울특별시,강남구,개포동,개포2차현대아파트(220),전세,77.75,48000,0,1.0,1988,2019,8,31,655-2,언주로 103,32
2,서울특별시,강남구,개포동,개포2차현대아파트(220),전세,77.75,55000,0,8.0,1988,2019,12,10,655-2,언주로 103,32
3,서울특별시,강남구,개포동,개포2차현대아파트(220),전세,77.75,65000,0,2.0,1988,2019,12,21,655-2,언주로 103,32
4,서울특별시,강남구,개포동,개포2차현대아파트(220),전세,77.75,53000,0,8.0,1988,2020,2,5,655-2,언주로 103,32
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168534,서울특별시,중랑구,중화동,한신2,전세,59.76,23500,0,4.0,1998,2015,6,26,450,동일로 752,22
168535,서울특별시,중랑구,중화동,한신2,전세,59.76,27000,0,22.0,1998,2015,7,30,450,동일로 752,22
168536,서울특별시,중랑구,중화동,한영(101),전세,71.83,19000,0,2.0,2003,2015,4,29,274-51,동일로144길 74,17
168538,서울특별시,중랑구,중화동,한영(103),월세,50.29,4000,50,5.0,2003,2015,3,6,274-76,동일로144길 74,17
168540,서울특별시,중랑구,중화동,한영(104),전세,67.57,17500,0,4.0,2003,2015,3,28,274-77,동일로144길 74,17

In [32]:
apt_rent_all1['category'].unique()

array(['전세', '월세'], dtype=object)

In [38]:
apt_rent_all1.to_excel('/Users/kang/Pandas/Real/apt_rent_all_new_1.xlsx')

In [39]:
apt_rent_all2.to_excel('/Users/kang/Pandas/Real/apt_rent_all_new_2.xlsx')