In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('/Users/kang/Documents/Github/Pandas/doit/data/highofficer_2018-2019.csv', encoding = 'CP949')

In [3]:
pd.options.display.float_format = '{:,}'.format

In [4]:
pd.set_option('precision', 1)

In [5]:
df.head()

,Unnamed: 0,소속_대분류,소속_소분류,소속,직위,성명,개별index,대분류,본인과의 관계,재산의 종류,소재지 면적 등 권리의 명세,종전가액,증가액,증가액_실거래가,감소액,감소액_실거래가,현재가액,변동사유,years
0,1,청와대,청와대,대통령,대통령,문재인,대통령-대통령-문재인,토지,본인,잡종지,경상남도 양산시 매곡동 28번지 159.00㎡,"20,177.0",0.0,0.0,0.0,0.0,"20,177.0",공시지가 변동없음,2018
1,2,청와대,청와대,대통령,대통령,문재인,대통령-대통령-문재인,토지,본인,주차장,경상남도 양산시 매곡동 29번지 577.00㎡,"73,221.0",0.0,0.0,0.0,0.0,"73,221.0",공시지가 변동없음,2018
2,3,청와대,청와대,대통령,대통령,문재인,대통령-대통령-문재인,토지,본인,답,경상남도 양산시 매곡동 30-2번지 15.00㎡,340.0,0.0,0.0,0.0,0.0,340.0,공시지가 변동없음,2018
3,4,청와대,청와대,대통령,대통령,문재인,대통령-대통령-문재인,토지,본인,답,경상남도 양산시 매곡동 30-3번지 14.00㎡,317.0,0.0,0.0,0.0,0.0,317.0,공시지가 변동없음,2018
4,5,청와대,청와대,대통령,대통령,문재인,대통령-대통령-문재인,토지,본인,답,경상남도 양산시 매곡동 30-4번지 47.00㎡,"1,066.0",0.0,0.0,0.0,0.0,"1,066.0",공시지가 변동없음,2018

In [6]:
df1=df[df['years']==2019]

In [7]:
df1['성명'].nunique()

2292

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 86174 entries, 0 to 86173
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       86174 non-null  int64
 1   소속_대분류           86174 non-null  object
 2   소속_소분류           86174 non-null  object
 3   소속               86174 non-null  object
 4   직위               85174 non-null  object
 5   성명               86174 non-null  object
 6   개별index          86174 non-null  object
 7   대분류              86174 non-null  object
 8   본인과의 관계          86174 non-null  object
 9   재산의 종류           70561 non-null  object
 10  소재지 면적 등 권리의 명세  85302 non-null  object
 11  종전가액             86174 non-null  float64
 12  증가액              86174 non-null  float64
 13  증가액_실거래가         86174 non-null  float64
 14  감소액              86174 non-null  float64
 15  감소액_실거래가         86174 non-null  float64
 16  현재가액             86174 non-null  float64
 17  변동사유             77151 non-null  object
 18  years            86174 non-null  int64
dtypes: float64(6), int64(2), object(11)
memory usage: 12.5+ MB

In [9]:
sum=df1.groupby(['성명'])['현재가액'].mean()
sum.sort_values(ascending=False)
sum1=sum.reset_index()
sum1=sum.to_frame()

In [10]:
sum

성명
가세로   58,066.608695652176
강경구   142,551.33333333334
강경화            141,169.48
강근식   22,786.342857142856
강길부   139,357.88888888888
              ...
황철규   118,982.38461538461
황치영   134,725.88235294117
황한식            175,900.04
황현택    66,130.47826086957
황희    31,193.666666666668
Name: 현재가액, Length: 2292, dtype: float64

In [11]:
df1.현재가액.apply(lambda x:"{:,}".format(x))

42447     23,913.0
42448     86,780.0
42449        355.0
42450        331.0
42451      1,113.0
           ...
86169     -5,000.0
86170     -5,000.0
86171    -20,000.0
86172          0.0
86173          0.0
Name: 현재가액, Length: 43727, dtype: object

In [12]:
kim.현재가액.apply(lambda x:"{:,}".format(x))

NameError: name 'kim' is not defined

In [ ]:
kim['현재가액'].sum()

In [13]:
kim.sum()

NameError: name 'kim' is not defined

In [14]:
kim=df1[df1['성명']=='김병관']
kim.groupby('대분류').sum()

,Unnamed: 0,종전가액,증가액,증가액_실거래가,감소액,감소액_실거래가,현재가액,years
대분류,,,,,,,,
건물,538678,"6,617,000.0",0.0,0.0,0.0,0.0,"6,617,000.0",14133
고지거부및등록제외사항,153945,0.0,0.0,0.0,0.0,0.0,0.0,4038
부동산에관한규정이준용되는권리와자동차-건설기계-선박및항공기,307838,"51,020.0","38,850.0",0.0,"20,140.0",0.0,"69,730.0",8076
예금,153925,"46,929,336.0","3,523,091.0",0.0,"8,180,256.0",0.0,"42,272,171.0",4038
유가증권,230898,"375,332,731.0","132,751,533.0",0.0,"295,271,250.0",0.0,"212,813,014.0",6057
정치자금법에따른정치자금의수입및지출을위한예금계좌의예금,76964,"54,163.0","61,146.0",0.0,"54,163.0",0.0,"61,146.0",2019
채권,153937,"14,190,000.0",0.0,0.0,0.0,0.0,"14,190,000.0",4038
합명-합자-유한회사출자지분,76971,"100,000.0",0.0,0.0,0.0,0.0,"100,000.0",2019
회원권,76970,"252,000.0",0.0,0.0,"12,000.0",0.0,"240,000.0",2019

In [15]:
kim['현재가액'].sum()

276363061.0

In [16]:
df['대분류'].unique()

array(['토지', '건물', '부동산에관한규정이준용되는권리와자동차-건설기계-선박및항공기', '예금', '채권', '채무',
       '지식재산권', '고지거부및등록제외사항', '유가증권', '합명-합자-유한회사출자지분', '회원권',
       '정치자금법에따른정치자금의수입및지출을위한예금계좌의예금', '현금', '골동품및예술품', '보석류', '금및백금',
       '비영리법인에출연한재산'], dtype=object)

In [17]:
df['지역']=df['소재지 면적 등 권리의 명세'].fillna('알수없음')

In [18]:
s=df[df['지역'].str.contains('성동')]
s

,Unnamed: 0,소속_대분류,소속_소분류,소속,직위,성명,개별index,대분류,본인과의 관계,재산의 종류,소재지 면적 등 권리의 명세,종전가액,증가액,증가액_실거래가,감소액,감소액_실거래가,현재가액,변동사유,years,지역
200,201,청와대,청와대,대통령비서실,경제수석비서관,홍장표,대통령비서실-경제수석비서관-홍장표,건물,본인,아파트전세(임차)권,서울특별시성동구금호동3가 두산아파트건물59.97㎡,0.0,"100,000.0",0.0,0.0,0.0,"100,000.0",전세보증금,2018,서울특별시성동구금호동3가 두산아파트건물59.97㎡
1432,1433,정부,국무총리실,국무총리비서실,민정실장,이상식,국무총리비서실-민정실장-이상식,건물,본인,아파트전세(임차)권,서울특별시강남구삼성동 현대힐스테이트2차건물84.0 ㎡,0.0,"940,000.0","940,000.0",0.0,0.0,"940,000.0",신규전세계약,2018,서울특별시강남구삼성동 현대힐스테이트2차건물84.0 ㎡
1483,1484,정부,인사혁신처,인사혁신처,처장,김판석,인사혁신처-처장-김판석,건물,본인,아파트,서울특별시 성동구 성수동2가 롯데캐슬파크 건물 81.58㎡중 40.79㎡,"218,000.0",0.0,0.0,0.0,0.0,"218,000.0",2017.1.1일 기준공동주택공시가격,2018,서울특별시 성동구 성수동2가 롯데캐슬파크 건물 81.58㎡중 40.79㎡
1484,1485,정부,인사혁신처,인사혁신처,처장,김판석,인사혁신처-처장-김판석,건물,배우자,아파트,서울특별시 성동구 성수동2가 롯데캐슬파크 건물 81.58㎡중 40.79㎡,"218,000.0",0.0,0.0,0.0,0.0,"218,000.0",2017.1.1일 기준공동주택공시가격,2018,서울특별시 성동구 성수동2가 롯데캐슬파크 건물 81.58㎡중 40.79㎡
1555,1556,정부,인사혁신처,인사혁신처소청심사위원회,상임위원,조명우,인사혁신처소청심사위원회-상임위원-조명우,토지,배우자,대지,서울특별시 성동구 성수동2가 342-10번지 10.00㎡ 중 1.66㎡,"6,626.0",193.0,0.0,0.0,0.0,"6,819.0",가액변동,2018,서울특별시 성동구 성수동2가 342-10번지 10.00㎡ 중 1.66㎡
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86115,86116,사법부,사법부,헌법재판소,재판관,이영진,헌법재판소-재판관-이영진,채무,본인,건물임대채무,서울특별시 성동구 행당동 임대보증금 증가,"-460,000.0","-20,000.0",0.0,0.0,0.0,"-480,000.0",전세보증금 증가,2019,서울특별시 성동구 행당동 임대보증금 증가
86118,86119,사법부,사법부,헌법재판소,사무처장,김헌정,헌법재판소-사무처장-김헌정,건물,본인,단독주택,서울특별시 강남구 삼성동 대지 226.70㎡ 중 151.14㎡ 건물 296.09㎡ ...,"1,450,000.0",0.0,0.0,0.0,0.0,"1,450,000.0",변동없음,2019,서울특별시 강남구 삼성동 대지 226.70㎡ 중 151.14㎡ 건물 296.09㎡ ...
86120,86121,사법부,사법부,헌법재판소,사무처장,김헌정,헌법재판소-사무처장-김헌정,건물,배우자,단독주택,서울특별시 강남구 삼성동 대지 226.70㎡ 중 75.56㎡건물 296.09㎡ 중 ...,"725,000.0",0.0,0.0,0.0,0.0,"725,000.0",변동없음,2019,서울특별시 강남구 삼성동 대지 226.70㎡ 중 75.56㎡건물 296.09㎡ 중 ...
86137,86138,사법부,사법부,헌법재판소,사무처장,김헌정,헌법재판소-사무처장-김헌정,채무,본인,건물임대채무,서울특별시 강남구 삼성동 임대보증금 감소,"-53,333.0",0.0,0.0,"-53,333.0",0.0,0.0,임대차 종료,2019,서울특별시 강남구 삼성동 임대보증금 감소
86140,86141,사법부,사법부,헌법재판소,사무처장,김헌정,헌법재판소-사무처장-김헌정,채무,배우자,건물임대채무,서울특별시 강남구 삼성동 임대보증금 감소,"-26,666.0",0.0,0.0,"-26,666.0",0.0,0.0,임대차 종료,2019,서울특별시 강남구 삼성동 임대보증금 감소

In [19]:
s.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 638 entries, 200 to 86140
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       638 non-null    int64
 1   소속_대분류           638 non-null    object
 2   소속_소분류           638 non-null    object
 3   소속               638 non-null    object
 4   직위               632 non-null    object
 5   성명               638 non-null    object
 6   개별index          638 non-null    object
 7   대분류              638 non-null    object
 8   본인과의 관계          638 non-null    object
 9   재산의 종류           633 non-null    object
 10  소재지 면적 등 권리의 명세  638 non-null    object
 11  종전가액             638 non-null    float64
 12  증가액              638 non-null    float64
 13  증가액_실거래가         638 non-null    float64
 14  감소액              638 non-null    float64
 15  감소액_실거래가         638 non-null    float64
 16  현재가액             638 non-null    float64
 17  변동사유             550 non-null    object
 18  years            638 non-null    int64
 19  지역               638 non-null    object
dtypes: float64(6), int64(2), object(12)
memory usage: 104.7+ KB

In [20]:
sum1['분위1']=pd.cut(sum1['현재가액'],bins=pd.interval_range(start=sum1['현재가액'].min(),end=sum1['현재가액'].max(),periods=5))

In [21]:
sum1

                   현재가액                                       분위1
성명
가세로 58,066.608695652176  (-126088.27272727272, 2302286.433992095]
강경구 142,551.33333333334  (-126088.27272727272, 2302286.433992095]
강경화          141,169.48  (-126088.27272727272, 2302286.433992095]
강근식 22,786.342857142856  (-126088.27272727272, 2302286.433992095]
강길부 139,357.88888888888  (-126088.27272727272, 2302286.433992095]
..                  ...                                       ...
황철규 118,982.38461538461  (-126088.27272727272, 2302286.433992095]
황치영 134,725.88235294117  (-126088.27272727272, 2302286.433992095]
황한식          175,900.04  (-126088.27272727272, 2302286.433992095]
황현택  66,130.47826086957  (-126088.27272727272, 2302286.433992095]
황희  31,193.666666666668  (-126088.27272727272, 2302286.433992095]

[2292 rows x 2 columns]

In [22]:
import numpy as np
a=np.quantile(sum1['현재가액'],[0,0.2,0.4,0.6,0.8,1])
a

array([ -126088.27272727,    22490.35833333,    44174.95857143,
          72171.05384615,   121012.05112782, 12015785.26086956])

In [23]:
sum1['분위']=pd.qcut(sum1['현재가액'],5,labels=["1","2","3","4","5"],duplicates='raise')

In [24]:
a=pd.qcut(sum1['현재가액'],5,labels=None,retbins=True,precision=0,duplicates='raise')

In [25]:
a

(성명
 가세로        (44175.0, 72171.0]
 강경구    (121012.0, 12015785.0]
 강경화    (121012.0, 12015785.0]
 강근식        (22490.0, 44175.0]
 강길부    (121012.0, 12015785.0]
                 ...
 황철규       (72171.0, 121012.0]
 황치영    (121012.0, 12015785.0]
 황한식    (121012.0, 12015785.0]
 황현택        (44175.0, 72171.0]
 황희         (22490.0, 44175.0]
 Name: 현재가액, Length: 2292, dtype: category
 Categories (5, interval[float64]): [(-126089.0, 22490.0] < (22490.0, 44175.0] < (44175.0, 72171.0] < (72171.0, 121012.0] < (121012.0, 12015785.0]],
 array([ -126088.27272727,    22490.35833333,    44174.95857143,
           72171.05384615,   121012.05112782, 12015785.26086956]))

In [26]:
sum1

                   현재가액                                       분위1 분위
성명
가세로 58,066.608695652176  (-126088.27272727272, 2302286.433992095]  3
강경구 142,551.33333333334  (-126088.27272727272, 2302286.433992095]  5
강경화          141,169.48  (-126088.27272727272, 2302286.433992095]  5
강근식 22,786.342857142856  (-126088.27272727272, 2302286.433992095]  2
강길부 139,357.88888888888  (-126088.27272727272, 2302286.433992095]  5
..                  ...                                       ... ..
황철규 118,982.38461538461  (-126088.27272727272, 2302286.433992095]  4
황치영 134,725.88235294117  (-126088.27272727272, 2302286.433992095]  5
황한식          175,900.04  (-126088.27272727272, 2302286.433992095]  5
황현택  66,130.47826086957  (-126088.27272727272, 2302286.433992095]  3
황희  31,193.666666666668  (-126088.27272727272, 2302286.433992095]  2

[2292 rows x 3 columns]

In [27]:
df_percentile=df1.merge(sum1,on=['성명'])

In [28]:
df_percentile

,Unnamed: 0,소속_대분류,소속_소분류,소속,직위,성명,개별index,대분류,본인과의 관계,재산의 종류,...,증가액,증가액_실거래가,감소액,감소액_실거래가,현재가액_x,변동사유,years,현재가액_y,분위1,분위
0,42448,청와대,청와대,대통령,대통령,문재인,대통령-대통령-문재인,토지,본인,잡종지,...,"3,736.0",0.0,0.0,0.0,"23,913.0",공시지가 변동,2019,"61,091.27272727273","(-126088.27272727272, 2302286.433992095]",3
1,42449,청와대,청와대,대통령,대통령,문재인,대통령-대통령-문재인,토지,본인,주차장,...,"13,559.0",0.0,0.0,0.0,"86,780.0",공시지가 변동,2019,"61,091.27272727273","(-126088.27272727272, 2302286.433992095]",3
2,42450,청와대,청와대,대통령,대통령,문재인,대통령-대통령-문재인,토지,본인,답,...,15.0,0.0,0.0,0.0,355.0,공시지가 변동,2019,"61,091.27272727273","(-126088.27272727272, 2302286.433992095]",3
3,42451,청와대,청와대,대통령,대통령,문재인,대통령-대통령-문재인,토지,본인,답,...,14.0,0.0,0.0,0.0,331.0,공시지가 변동,2019,"61,091.27272727273","(-126088.27272727272, 2302286.433992095]",3
4,42452,청와대,청와대,대통령,대통령,문재인,대통령-대통령-문재인,토지,본인,답,...,47.0,0.0,0.0,0.0,"1,113.0",공시지가 변동,2019,"61,091.27272727273","(-126088.27272727272, 2302286.433992095]",3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43722,86148,사법부,사법부,헌법재판소,헌법재판연구원장,석인선,헌법재판소-헌법재판연구원장-석인선,부동산에관한규정이준용되는권리와자동차-건설기계-선박및항공기,배우자,자동차,...,0.0,0.0,"1,560.0",0.0,"5,040.0",가액변동,2019,"-16,664.285714285714","(-126088.27272727272, 2302286.433992095]",1
43723,86149,사법부,사법부,헌법재판소,헌법재판연구원장,석인선,헌법재판소-헌법재판연구원장-석인선,예금,본인,NaN,...,"21,008.0",0.0,"30,513.0",0.0,"228,714.0","채무 상환, 저축연금 일부 지급받음",2019,"-16,664.285714285714","(-126088.27272727272, 2302286.433992095]",1
43724,86150,사법부,사법부,헌법재판소,헌법재판연구원장,석인선,헌법재판소-헌법재판연구원장-석인선,예금,배우자,NaN,...,"1,288.0",0.0,"2,377.0",0.0,"14,202.0","채무 상환, 저축연금 일부 지급받음",2019,"-16,664.285714285714","(-126088.27272727272, 2302286.433992095]",1
43725,86151,사법부,사법부,헌법재판소,헌법재판연구원장,석인선,헌법재판소-헌법재판연구원장-석인선,채무,본인,금융기관채무,...,"-14,920.0",0.0,"-64,734.0",0.0,"-373,748.0",일부 상환,2019,"-16,664.285714285714","(-126088.27272727272, 2302286.433992095]",1
43726,86152,사법부,사법부,헌법재판소,헌법재판연구원장,석인선,헌법재판소-헌법재판연구원장-석인선,채무,배우자,금융기관채무,...,0.0,0.0,0.0,0.0,"-258,000.0",변동없음,2019,"-16,664.285714285714","(-126088.27272727272, 2302286.433992095]",1

In [29]:
df_percentile.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 43727 entries, 0 to 43726
Data columns (total 22 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       43727 non-null  int64
 1   소속_대분류           43727 non-null  object
 2   소속_소분류           43727 non-null  object
 3   소속               43727 non-null  object
 4   직위               43284 non-null  object
 5   성명               43727 non-null  object
 6   개별index          43727 non-null  object
 7   대분류              43727 non-null  object
 8   본인과의 관계          43727 non-null  object
 9   재산의 종류           40526 non-null  object
 10  소재지 면적 등 권리의 명세  43719 non-null  object
 11  종전가액             43727 non-null  float64
 12  증가액              43727 non-null  float64
 13  증가액_실거래가         43727 non-null  float64
 14  감소액              43727 non-null  float64
 15  감소액_실거래가         43727 non-null  float64
 16  현재가액_x           43727 non-null  float64
 17  변동사유             38354 non-null  object
 18  years            43727 non-null  int64
 19  현재가액_y           43727 non-null  float64
 20  분위1              43716 non-null  category
 21  분위               43727 non-null  category
dtypes: category(2), float64(7), int64(2), object(11)
memory usage: 7.1+ MB

In [30]:
df_percentile.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 43727 entries, 0 to 43726
Data columns (total 22 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       43727 non-null  int64
 1   소속_대분류           43727 non-null  object
 2   소속_소분류           43727 non-null  object
 3   소속               43727 non-null  object
 4   직위               43284 non-null  object
 5   성명               43727 non-null  object
 6   개별index          43727 non-null  object
 7   대분류              43727 non-null  object
 8   본인과의 관계          43727 non-null  object
 9   재산의 종류           40526 non-null  object
 10  소재지 면적 등 권리의 명세  43719 non-null  object
 11  종전가액             43727 non-null  float64
 12  증가액              43727 non-null  float64
 13  증가액_실거래가         43727 non-null  float64
 14  감소액              43727 non-null  float64
 15  감소액_실거래가         43727 non-null  float64
 16  현재가액_x           43727 non-null  float64
 17  변동사유             38354 non-null  object
 18  years            43727 non-null  int64
 19  현재가액_y           43727 non-null  float64
 20  분위1              43716 non-null  category
 21  분위               43727 non-null  category
dtypes: category(2), float64(7), int64(2), object(11)
memory usage: 7.1+ MB

In [31]:
del df_percentile['현재가액_y']

In [32]:
df_percentile.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 43727 entries, 0 to 43726
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       43727 non-null  int64
 1   소속_대분류           43727 non-null  object
 2   소속_소분류           43727 non-null  object
 3   소속               43727 non-null  object
 4   직위               43284 non-null  object
 5   성명               43727 non-null  object
 6   개별index          43727 non-null  object
 7   대분류              43727 non-null  object
 8   본인과의 관계          43727 non-null  object
 9   재산의 종류           40526 non-null  object
 10  소재지 면적 등 권리의 명세  43719 non-null  object
 11  종전가액             43727 non-null  float64
 12  증가액              43727 non-null  float64
 13  증가액_실거래가         43727 non-null  float64
 14  감소액              43727 non-null  float64
 15  감소액_실거래가         43727 non-null  float64
 16  현재가액_x           43727 non-null  float64
 17  변동사유             38354 non-null  object
 18  years            43727 non-null  int64
 19  분위1              43716 non-null  category
 20  분위               43727 non-null  category
dtypes: category(2), float64(6), int64(2), object(11)
memory usage: 6.8+ MB

In [33]:
df_percentile1=df_percentile.rename(columns={'현재가액_x': '현재가액'})

In [34]:
df_percentile1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 43727 entries, 0 to 43726
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       43727 non-null  int64
 1   소속_대분류           43727 non-null  object
 2   소속_소분류           43727 non-null  object
 3   소속               43727 non-null  object
 4   직위               43284 non-null  object
 5   성명               43727 non-null  object
 6   개별index          43727 non-null  object
 7   대분류              43727 non-null  object
 8   본인과의 관계          43727 non-null  object
 9   재산의 종류           40526 non-null  object
 10  소재지 면적 등 권리의 명세  43719 non-null  object
 11  종전가액             43727 non-null  float64
 12  증가액              43727 non-null  float64
 13  증가액_실거래가         43727 non-null  float64
 14  감소액              43727 non-null  float64
 15  감소액_실거래가         43727 non-null  float64
 16  현재가액             43727 non-null  float64
 17  변동사유             38354 non-null  object
 18  years            43727 non-null  int64
 19  분위1              43716 non-null  category
 20  분위               43727 non-null  category
dtypes: category(2), float64(6), int64(2), object(11)
memory usage: 6.8+ MB

In [35]:
portfolio=df_percentile1.groupby(['분위','대분류'])['현재가액'].sum()

In [36]:
portfolio_mean=df_percentile1.groupby(['분위','대분류'])['현재가액'].mean()
portfolio_mean.to_frame()
portfolio_mean

분위  대분류
1   건물                111,118.85231023103
    고지거부및등록제외사항                       0.0
    골동품및예술품            21,854.83870967742
    금및백금                        11,004.65
    보석류                          26,475.0
                             ...
5   채무               -246,409.83706070288
    토지                123,162.43060038735
    합명-합자-유한회사출자지분    206,222.73076923078
    현금                56,246.444444444445
    회원권               53,250.837004405286
Name: 현재가액, Length: 85, dtype: float64

In [37]:
portfolio_mean.to_excel()

TypeError: to_excel() missing 1 required positional argument: 'excel_writer'

In [38]:
portfolio_mean.to_excel("/Users/kang/Documents/Github/Pandas/Exercise/portfolio_mean.xlsx")

In [39]:
portfolio

분위  대분류
1   건물                134,676,049.0
    고지거부및등록제외사항                 0.0
    골동품및예술품             1,355,000.0
    금및백금                  220,093.0
    보석류                   132,375.0
                          ...
5   채무               -231,378,837.0
    토지                190,778,605.0
    합명-합자-유한회사출자지분      5,361,791.0
    현금                  1,518,654.0
    회원권                12,087,940.0
Name: 현재가액, Length: 85, dtype: float64

In [40]:
portfolio1=portfolio.to_frame()

In [41]:
portfolio1

                            현재가액
분위 대분류
1  건물              134,676,049.0
   고지거부및등록제외사항               0.0
   골동품및예술품           1,355,000.0
   금및백금                220,093.0
   보석류                 132,375.0
...                          ...
5  채무             -231,378,837.0
   토지              190,778,605.0
   합명-합자-유한회사출자지분    5,361,791.0
   현금                1,518,654.0
   회원권              12,087,940.0

[85 rows x 1 columns]

In [42]:
a=portfolio1.reset_index()

In [43]:
a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85 entries, 0 to 84
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   분위      85 non-null     category
 1   대분류     85 non-null     object
 2   현재가액    85 non-null     float64
dtypes: category(1), float64(1), object(1)
memory usage: 1.7+ KB

In [44]:
a

   분위             대분류           현재가액
0   1              건물  134,676,049.0
1   1     고지거부및등록제외사항            0.0
2   1         골동품및예술품    1,355,000.0
3   1            금및백금      220,093.0
4   1             보석류      132,375.0
.. ..             ...            ...
80  5              채무 -231,378,837.0
81  5              토지  190,778,605.0
82  5  합명-합자-유한회사출자지분    5,361,791.0
83  5              현금    1,518,654.0
84  5             회원권   12,087,940.0

[85 rows x 3 columns]

In [45]:
s=a.groupby('분위')['현재가액'].mean
s

In [46]:
s.to_frame()

AttributeError: 'function' object has no attribute 'to_frame'

In [47]:
s.to_excel("/Users/kang/Documents/Github/Pandas/Exercise/portfolio_mean.xlsx")

AttributeError: 'function' object has no attribute 'to_excel'

In [48]:
e

NameError: name 'e' is not defined

In [49]:
df_percentile1

,Unnamed: 0,소속_대분류,소속_소분류,소속,직위,성명,개별index,대분류,본인과의 관계,재산의 종류,...,종전가액,증가액,증가액_실거래가,감소액,감소액_실거래가,현재가액,변동사유,years,분위1,분위
0,42448,청와대,청와대,대통령,대통령,문재인,대통령-대통령-문재인,토지,본인,잡종지,...,"20,177.0","3,736.0",0.0,0.0,0.0,"23,913.0",공시지가 변동,2019,"(-126088.27272727272, 2302286.433992095]",3
1,42449,청와대,청와대,대통령,대통령,문재인,대통령-대통령-문재인,토지,본인,주차장,...,"73,221.0","13,559.0",0.0,0.0,0.0,"86,780.0",공시지가 변동,2019,"(-126088.27272727272, 2302286.433992095]",3
2,42450,청와대,청와대,대통령,대통령,문재인,대통령-대통령-문재인,토지,본인,답,...,340.0,15.0,0.0,0.0,0.0,355.0,공시지가 변동,2019,"(-126088.27272727272, 2302286.433992095]",3
3,42451,청와대,청와대,대통령,대통령,문재인,대통령-대통령-문재인,토지,본인,답,...,317.0,14.0,0.0,0.0,0.0,331.0,공시지가 변동,2019,"(-126088.27272727272, 2302286.433992095]",3
4,42452,청와대,청와대,대통령,대통령,문재인,대통령-대통령-문재인,토지,본인,답,...,"1,066.0",47.0,0.0,0.0,0.0,"1,113.0",공시지가 변동,2019,"(-126088.27272727272, 2302286.433992095]",3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43722,86148,사법부,사법부,헌법재판소,헌법재판연구원장,석인선,헌법재판소-헌법재판연구원장-석인선,부동산에관한규정이준용되는권리와자동차-건설기계-선박및항공기,배우자,자동차,...,"6,600.0",0.0,0.0,"1,560.0",0.0,"5,040.0",가액변동,2019,"(-126088.27272727272, 2302286.433992095]",1
43723,86149,사법부,사법부,헌법재판소,헌법재판연구원장,석인선,헌법재판소-헌법재판연구원장-석인선,예금,본인,NaN,...,"238,219.0","21,008.0",0.0,"30,513.0",0.0,"228,714.0","채무 상환, 저축연금 일부 지급받음",2019,"(-126088.27272727272, 2302286.433992095]",1
43724,86150,사법부,사법부,헌법재판소,헌법재판연구원장,석인선,헌법재판소-헌법재판연구원장-석인선,예금,배우자,NaN,...,"15,291.0","1,288.0",0.0,"2,377.0",0.0,"14,202.0","채무 상환, 저축연금 일부 지급받음",2019,"(-126088.27272727272, 2302286.433992095]",1
43725,86151,사법부,사법부,헌법재판소,헌법재판연구원장,석인선,헌법재판소-헌법재판연구원장-석인선,채무,본인,금융기관채무,...,"-423,562.0","-14,920.0",0.0,"-64,734.0",0.0,"-373,748.0",일부 상환,2019,"(-126088.27272727272, 2302286.433992095]",1
43726,86152,사법부,사법부,헌법재판소,헌법재판연구원장,석인선,헌법재판소-헌법재판연구원장-석인선,채무,배우자,금융기관채무,...,"-258,000.0",0.0,0.0,0.0,0.0,"-258,000.0",변동없음,2019,"(-126088.27272727272, 2302286.433992095]",1

In [50]:
increase_=df_percentile1.groupby(['분위','대분류'])['증가액'].sum()
increase=increase_.to_frame().reset_index()
increase.drop(increase.loc[increase['대분류']=='채무'].index,inplace=True)
increase.groupby('대분류')['증가액'].unique()

대분류
건물                                 [15151437.0, 42082772.0, 61576539.0, 91622822....
고지거부및등록제외사항                                                                    [0.0]
골동품및예술품                                                              [0.0, 120000.0]
금및백금                                       [7253.0, 1414.0, 5894.0, 6598.0, 97004.0]
보석류                                                          [80000.0, 0.0, 25050.0]
부동산에관한규정이준용되는권리와자동차-건설기계-선박및항공기    [3470911.0, 2854490.0, 2808485.0, 4366887.0, 2...
비영리법인에출연한재산                                                                    [0.0]
예금                                 [16988562.0, 37975062.0, 61254433.0, 101876246...
유가증권                               [1079304.0, 3624144.0, 4832570.0, 6408936.0, 1...
정치자금법에따른정치자금의수입및지출을위한예금계좌의예금       [449658.0, 1174097.0, 2242463.0, 3115809.0, 27...
지식재산권                                                                          [0.0]
채권                                 [1192595.0, 1614326.0, 4109986.0, 4819781.0, 1...
토지                                 [3595135.0, 6350549.0, 6523412.0, 10658237.0, ...
합명-합자-유한회사출자지분                     [121270.0, 662966.0, 150000.0, 627435.0, 80411...
현금                                  [195000.0, 534750.0, 15000.0, 43500.0, 406639.0]
회원권                                 [23560.0, 35000.0, 254300.0, 199788.0, 879681.0]
Name: 증가액, dtype: object

In [51]:
c = df.groupby(['state', 'office_id'])['sales'].sum().rename("count")
 c / c.groupby(level=0).sum()
    
    df['%'] = 100 * df['sales'] / df.groupby('state')['sales'].transform('sum')
     df.groupby(['Country','Date']).agg(lambda x: x[x>0].mean())

IndentationError: unexpected indent (<ipython-input-51-d17111207273>, line 2)

In [52]:
increase['증가율']=100*increase['증가액']/increase.groupby(['분위'])['증가액'].transform('sum')

In [53]:
pd.options.display.float_format = "{:,.1f}".format

In [54]:
increase

   분위             대분류          증가액  증가율
0   1              건물 15,151,437.0 35.8
1   1     고지거부및등록제외사항          0.0  0.0
2   1         골동품및예술품          0.0  0.0
3   1            금및백금      7,253.0  0.0
4   1             보석류     80,000.0  0.2
.. ..             ...          ...  ...
79  5              채권 11,895,887.0  2.0
81  5              토지 18,115,509.0  3.0
82  5  합명-합자-유한회사출자지분    804,119.0  0.1
83  5              현금    406,639.0  0.1
84  5             회원권    879,681.0  0.1

[80 rows x 4 columns]

In [55]:
df_pct = (df.groupby(['STRAT','Class'])['value'].count()/df.groupby(['STRAT'])['value'].count())
df_pct.unstack().plot.bar(stacked=True)

KeyError: 'STRAT'

In [56]:
sub_df1 = pd.DataFrame(d.values(), columns=['count'], index=pd.MultiIndex.from_tuples(d.keys()))
sub_df2 = sub_df1.unstack()
sub_df2.columns = sub_df2.columns.droplevel()  # Drop `count` label.
sub_df2 = sub_df2.div(sub_df2.sum())
sub_df2.T.plot(kind='bar', stacked=True, rot=1, figsize=(8, 8), 
               title="Home ownership across Loan Types")

NameError: name 'd' is not defined

In [57]:
pivot_df = df.pivot(index='Year', columns='Month', values='Value')
pivot_df

KeyError: 'Year'

In [ ]:
pivot_increase=increase.pivot(index='분위',columns='대분류',values='증가율')
pivot_increase

In [58]:
pivot_increase.plot.bar(stacked=True, figsize=(10,7))

NameError: name 'pivot_increase' is not defined

In [59]:
df_percentile.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 43727 entries, 0 to 43726
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       43727 non-null  int64
 1   소속_대분류           43727 non-null  object
 2   소속_소분류           43727 non-null  object
 3   소속               43727 non-null  object
 4   직위               43284 non-null  object
 5   성명               43727 non-null  object
 6   개별index          43727 non-null  object
 7   대분류              43727 non-null  object
 8   본인과의 관계          43727 non-null  object
 9   재산의 종류           40526 non-null  object
 10  소재지 면적 등 권리의 명세  43719 non-null  object
 11  종전가액             43727 non-null  float64
 12  증가액              43727 non-null  float64
 13  증가액_실거래가         43727 non-null  float64
 14  감소액              43727 non-null  float64
 15  감소액_실거래가         43727 non-null  float64
 16  현재가액_x           43727 non-null  float64
 17  변동사유             38354 non-null  object
 18  years            43727 non-null  int64
 19  분위1              43716 non-null  category
 20  분위               43727 non-null  category
dtypes: category(2), float64(6), int64(2), object(11)
memory usage: 6.8+ MB

In [60]:
building=df_percentile[df_percentile['대분류']=='건물']

In [61]:
building['재산의 종류'].unique()

array(['단독주택', '근린생활시설', '아파트', '아파트전세(임차)권', '다가구주택전세(임차)권', '상가',
       '연립주택전세(임차)권', '오피스텔전세(임차)권', '오피스텔', '복합건물(주택+상가)', '단독주택전세(임차)권',
       '상가전세(임차)권', '연립주택', '아파트(분양권)', '다세대주택', '다세대주택전세(임차)권',
       '근린생활시설전세(임차)권', '사무실전세(임차)권', '사무실', '기타', '숙박시설', '기타전세(임차)권',
       '창고', '다가구주택', '오피스텔(분양권)', '공장', '자동차관련시설', '업무시설', '빌딩전세(임차)권',
       '복합건물(주택+상가)전세(임차)권', '다세대주택(분양권)', '운동시설', '빌딩', '전세(임차)권',
       '농어가주택', '의료시설', '교육연구및복지시설전세(임차)권', '위락시설(분양권)', '기숙사전세(임차)권',
       '상가(분양권)', '단독주택(분양권)', '근린생활시설(분양권)', '의료시설전세(임차)권', '묘지관련시설',
       '복합건물(주택+상가)(분양권)', '공장전세(임차)권', '교육연구및복지시설', '위락시설', '주유(충전)소',
       '기타건물', '단독주택,경량철골조', '창고전세(임차)권', '기타(분양권)', '주택', '숙박시설(분양권)',
       '문화및집회시설', '업무시설및근린생활시설', '식품위생시설', '주택겸근린생활시설', '차량관리시설', '복합건물',
       '체육시설', '축사', '근린생활시설및업무시설', '농업생산시설'], dtype=object)

In [62]:
building['재산의 종류'].astype(str)

11             단독주택
12           근린생활시설
13             단독주택
14              아파트
33              아파트
            ...
43697          오피스텔
43698    아파트전세(임차)권
43699         다세대주택
43700       자동차관련시설
43721           아파트
Name: 재산의 종류, Length: 8439, dtype: object

In [63]:
building.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8439 entries, 11 to 43721
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       8439 non-null   int64
 1   소속_대분류           8439 non-null   object
 2   소속_소분류           8439 non-null   object
 3   소속               8439 non-null   object
 4   직위               8337 non-null   object
 5   성명               8439 non-null   object
 6   개별index          8439 non-null   object
 7   대분류              8439 non-null   object
 8   본인과의 관계          8439 non-null   object
 9   재산의 종류           8439 non-null   object
 10  소재지 면적 등 권리의 명세  8439 non-null   object
 11  종전가액             8439 non-null   float64
 12  증가액              8439 non-null   float64
 13  증가액_실거래가         8439 non-null   float64
 14  감소액              8439 non-null   float64
 15  감소액_실거래가         8439 non-null   float64
 16  현재가액_x           8439 non-null   float64
 17  변동사유             7387 non-null   object
 18  years            8439 non-null   int64
 19  분위1              8437 non-null   category
 20  분위               8439 non-null   category
dtypes: category(2), float64(6), int64(2), object(11)
memory usage: 1.3+ MB

In [64]:
apartment=building[['재산의 종류'].str.contains("아파트")]

AttributeError: 'list' object has no attribute 'str'

In [65]:
apartment=building[building['재산의 종류'].isin(['아파트','아파트전세(임차)권','아파트(분양권)'])]

In [66]:
apartment['재산의 종류'].unique()

array(['아파트', '아파트전세(임차)권', '아파트(분양권)'], dtype=object)

In [67]:
apartment

,Unnamed: 0,소속_대분류,소속_소분류,소속,직위,성명,개별index,대분류,본인과의 관계,재산의 종류,...,종전가액,증가액,증가액_실거래가,감소액,감소액_실거래가,현재가액_x,변동사유,years,분위1,분위
14,42462,청와대,청와대,대통령,대통령,문재인,대통령-대통령-문재인,건물,모,아파트,...,"127,000.0",0.0,0.0,0.0,0.0,"127,000.0",가액 변동없음,2019,"(-126088.27272727272, 2302286.433992095]",3
33,42481,청와대,청와대,대통령비서실,정책실장,김수현,대통령비서실-정책실장-김수현,건물,본인,아파트,...,"648,000.0","64,800.0",0.0,0.0,0.0,"712,800.0",가액변동,2019,"(-126088.27272727272, 2302286.433992095]",4
34,42482,청와대,청와대,대통령비서실,정책실장,김수현,대통령비서실-정책실장-김수현,건물,본인,아파트전세(임차)권,...,"500,000.0",0.0,0.0,0.0,0.0,"500,000.0",NaN,2019,"(-126088.27272727272, 2302286.433992095]",4
47,42495,청와대,청와대,대통령비서실,민정수석비서관,조국,대통령비서실-민정수석비서관-조국,건물,본인,아파트,...,"774,000.0","154,000.0",0.0,0.0,0.0,"928,000.0",가액변동,2019,"(-126088.27272727272, 2302286.433992095]",5
69,42517,청와대,청와대,대통령비서실,시민사회수석비서관,이용선,대통령비서실-시민사회수석비서관-이용선,건물,배우자,아파트,...,"316,000.0",0.0,0.0,0.0,0.0,"316,000.0",NaN,2019,"(-126088.27272727272, 2302286.433992095]",1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43677,86103,사법부,사법부,헌법재판소,재판관,이영진,헌법재판소-재판관-이영진,건물,본인,아파트,...,"365,000.0","43,000.0",0.0,0.0,0.0,"408,000.0",가액변동,2019,"(-126088.27272727272, 2302286.433992095]",4
43678,86104,사법부,사법부,헌법재판소,재판관,이영진,헌법재판소-재판관-이영진,건물,배우자,아파트,...,"317,000.0","7,000.0",0.0,0.0,0.0,"324,000.0",가액변동,2019,"(-126088.27272727272, 2302286.433992095]",4
43694,86120,사법부,사법부,헌법재판소,사무처장,김헌정,헌법재판소-사무처장-김헌정,건물,본인,아파트전세(임차)권,...,"810,000.0",0.0,0.0,"810,000.0",0.0,0.0,임대차 종료,2019,"(-126088.27272727272, 2302286.433992095]",5
43698,86124,사법부,사법부,헌법재판소,사무처장,김헌정,헌법재판소-사무처장-김헌정,건물,배우자,아파트전세(임차)권,...,"150,000.0",0.0,0.0,0.0,0.0,"150,000.0",변동없음,2019,"(-126088.27272727272, 2302286.433992095]",5
43721,86147,사법부,사법부,헌법재판소,헌법재판연구원장,석인선,헌법재판소-헌법재판연구원장-석인선,건물,배우자,아파트,...,"236,000.0","28,000.0",0.0,0.0,0.0,"264,000.0",가액변동,2019,"(-126088.27272727272, 2302286.433992095]",1

In [68]:
apartment['광역시']=apartment['소재지 면적 등 권리의 명세'].str.split(' ').str[0]

/Users/kang/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [93]:
apartment['자치구']=apartment['소재지 면적 등 권리의 명세'].str.split(' ').str[1]

/Users/kang/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [94]:
apartment

,Unnamed: 0,소속_대분류,소속_소분류,소속,직위,성명,개별index,대분류,본인과의 관계,재산의 종류,...,증가액_실거래가,감소액,감소액_실거래가,현재가액_x,변동사유,years,분위1,분위,광역시,자치구
14,42462,청와대,청와대,대통령,대통령,문재인,대통령-대통령-문재인,건물,모,아파트,...,0.0,0.0,0.0,"127,000.0",가액 변동없음,2019,"(-126088.27272727272, 2302286.433992095]",3,부산,영도구
33,42481,청와대,청와대,대통령비서실,정책실장,김수현,대통령비서실-정책실장-김수현,건물,본인,아파트,...,0.0,0.0,0.0,"712,800.0",가액변동,2019,"(-126088.27272727272, 2302286.433992095]",4,경기도,과천시
34,42482,청와대,청와대,대통령비서실,정책실장,김수현,대통령비서실-정책실장-김수현,건물,본인,아파트전세(임차)권,...,0.0,0.0,0.0,"500,000.0",NaN,2019,"(-126088.27272727272, 2302286.433992095]",4,경기도,과천시
47,42495,청와대,청와대,대통령비서실,민정수석비서관,조국,대통령비서실-민정수석비서관-조국,건물,본인,아파트,...,0.0,0.0,0.0,"928,000.0",가액변동,2019,"(-126088.27272727272, 2302286.433992095]",5,서울,서초구
69,42517,청와대,청와대,대통령비서실,시민사회수석비서관,이용선,대통령비서실-시민사회수석비서관-이용선,건물,배우자,아파트,...,0.0,0.0,0.0,"316,000.0",NaN,2019,"(-126088.27272727272, 2302286.433992095]",1,서울,양천구
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43677,86103,사법부,사법부,헌법재판소,재판관,이영진,헌법재판소-재판관-이영진,건물,본인,아파트,...,0.0,0.0,0.0,"408,000.0",가액변동,2019,"(-126088.27272727272, 2302286.433992095]",4,서울,성동구
43678,86104,사법부,사법부,헌법재판소,재판관,이영진,헌법재판소-재판관-이영진,건물,배우자,아파트,...,0.0,0.0,0.0,"324,000.0",가액변동,2019,"(-126088.27272727272, 2302286.433992095]",4,경기도,용인시
43694,86120,사법부,사법부,헌법재판소,사무처장,김헌정,헌법재판소-사무처장-김헌정,건물,본인,아파트전세(임차)권,...,0.0,"810,000.0",0.0,0.0,임대차 종료,2019,"(-126088.27272727272, 2302286.433992095]",5,서울,서초구
43698,86124,사법부,사법부,헌법재판소,사무처장,김헌정,헌법재판소-사무처장-김헌정,건물,배우자,아파트전세(임차)권,...,0.0,0.0,0.0,"150,000.0",변동없음,2019,"(-126088.27272727272, 2302286.433992095]",5,부산,남구
43721,86147,사법부,사법부,헌법재판소,헌법재판연구원장,석인선,헌법재판소-헌법재판연구원장-석인선,건물,배우자,아파트,...,0.0,0.0,0.0,"264,000.0",가액변동,2019,"(-126088.27272727272, 2302286.433992095]",1,서울,서대문구

In [95]:
apartment.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4150 entries, 14 to 43721
Data columns (total 23 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       4150 non-null   int64
 1   소속_대분류           4150 non-null   object
 2   소속_소분류           4150 non-null   object
 3   소속               4150 non-null   object
 4   직위               4103 non-null   object
 5   성명               4150 non-null   object
 6   개별index          4150 non-null   object
 7   대분류              4150 non-null   object
 8   본인과의 관계          4150 non-null   object
 9   재산의 종류           4150 non-null   object
 10  소재지 면적 등 권리의 명세  4150 non-null   object
 11  종전가액             4150 non-null   float64
 12  증가액              4150 non-null   float64
 13  증가액_실거래가         4150 non-null   float64
 14  감소액              4150 non-null   float64
 15  감소액_실거래가         4150 non-null   float64
 16  현재가액_x           4150 non-null   float64
 17  변동사유             3660 non-null   object
 18  years            4150 non-null   int64
 19  분위1              4149 non-null   category
 20  분위               4150 non-null   category
 21  광역시              4150 non-null   object
 22  자치구              4149 non-null   object
dtypes: category(2), float64(6), int64(2), object(13)
memory usage: 721.8+ KB

In [74]:
apartment['광역시']=apartment['광역시'].str.replace('세종특별자치시','세종')

/Users/kang/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [75]:
import numpy as np

In [76]:
apartment.loc[apartment['광역시'].str.contains('서울',case=False),'광역시']='서울'
apartment.loc[apartment['광역시'].str.contains('부산',case=False),'광역시']='부산'
apartment.loc[apartment['광역시'].str.contains('경기',case=False),'광역시']='경기도'
apartment.loc[apartment['광역시'].str.contains('대구',case=False),'광역시']='대구'
apartment.loc[apartment['광역시'].str.contains('대전',case=False),'광역시']='대전'
apartment.loc[apartment['광역시'].str.contains('강원',case=False),'광역시']='강원도'
apartment.loc[apartment['광역시'].str.contains('세종',case=False),'광역시']='세종'
apartment.loc[apartment['광역시'].str.contains('경상',case=False),'광역시']='경상도'
apartment.loc[apartment['광역시'].str.contains('울산',case=False),'광역시']='울산'
apartment.loc[apartment['광역시'].str.contains('전라',case=False),'광역시']='전라도'
apartment.loc[apartment['광역시'].str.contains('충청',case=False),'광역시']='충청도'
apartment.loc[apartment['광역시'].str.contains('광주',case=False),'광역시']='광주'
apartment.loc[apartment['광역시'].str.contains('제주',case=False),'광역시']='제주'
apartment.loc[apartment['광역시'].str.contains('충북',case=False),'광역시']='충청도'
apartment.loc[apartment['광역시'].str.contains('인천',case=False),'광역시']='인천'
apartment.loc[apartment['광역시'].str.contains('경북',case=False),'광역시']='경상도'
apartment.loc[apartment['광역시'].str.contains('전남',case=False),'광역시']='전라도'
apartment.loc[apartment['광역시'].str.contains('전북',case=False),'광역시']='전라도'
apartment.loc[apartment['광역시'].str.contains('중국',case=False),'광역시']='해외'
apartment.loc[apartment['광역시'].str.contains('동경',case=False),'광역시']='해외'
apartment.loc[apartment['광역시'].str.contains('s',case=False),'광역시']='해외'
apartment.loc[apartment['광역시'].str.contains('a',case=False),'광역시']='해외'
apartment.loc[apartment['광역시'].str.contains('오산동',case=False),'광역시']='경기도'

/Users/kang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:965: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

In [96]:
seoul=apartment[apartment['광역시']=='서울']

In [97]:
seoul

,Unnamed: 0,소속_대분류,소속_소분류,소속,직위,성명,개별index,대분류,본인과의 관계,재산의 종류,...,증가액_실거래가,감소액,감소액_실거래가,현재가액_x,변동사유,years,분위1,분위,광역시,자치구
47,42495,청와대,청와대,대통령비서실,민정수석비서관,조국,대통령비서실-민정수석비서관-조국,건물,본인,아파트,...,0.0,0.0,0.0,"928,000.0",가액변동,2019,"(-126088.27272727272, 2302286.433992095]",5,서울,서초구
69,42517,청와대,청와대,대통령비서실,시민사회수석비서관,이용선,대통령비서실-시민사회수석비서관-이용선,건물,배우자,아파트,...,0.0,0.0,0.0,"316,000.0",NaN,2019,"(-126088.27272727272, 2302286.433992095]",1,서울,양천구
105,42535,청와대,청와대,대통령비서실,인사수석비서관,조현옥,대통령비서실-인사수석비서관-조현옥,건물,본인,아파트,...,0.0,0.0,0.0,"320,000.0",NaN,2019,"(-126088.27272727272, 2302286.433992095]",3,서울,강서구
106,42536,청와대,청와대,대통령비서실,인사수석비서관,조현옥,대통령비서실-인사수석비서관-조현옥,건물,본인,아파트전세(임차)권,...,0.0,0.0,0.0,"250,000.0",NaN,2019,"(-126088.27272727272, 2302286.433992095]",3,서울,중구
115,42545,청와대,청와대,대통령비서실,일자리수석비서관,정태호,대통령비서실-일자리수석비서관-정태호,건물,본인,아파트,...,0.0,0.0,0.0,"334,000.0",가액변동,2019,"(-126088.27272727272, 2302286.433992095]",4,서울,관악구
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43648,86074,사법부,사법부,헌법재판소,재판관,이은애,헌법재판소-재판관-이은애,건물,배우자,아파트전세(임차)권,...,0.0,0.0,0.0,"400,000.0",NaN,2019,"(-126088.27272727272, 2302286.433992095]",4,서울,서초구
43659,86085,사법부,사법부,헌법재판소,재판관,이종석,헌법재판소-재판관-이종석,건물,본인,아파트,...,0.0,0.0,0.0,"1,416,750.0",변동없음,2019,"(-126088.27272727272, 2302286.433992095]",5,서울,서초구
43677,86103,사법부,사법부,헌법재판소,재판관,이영진,헌법재판소-재판관-이영진,건물,본인,아파트,...,0.0,0.0,0.0,"408,000.0",가액변동,2019,"(-126088.27272727272, 2302286.433992095]",4,서울,성동구
43694,86120,사법부,사법부,헌법재판소,사무처장,김헌정,헌법재판소-사무처장-김헌정,건물,본인,아파트전세(임차)권,...,0.0,"810,000.0",0.0,0.0,임대차 종료,2019,"(-126088.27272727272, 2302286.433992095]",5,서울,서초구
43721,86147,사법부,사법부,헌법재판소,헌법재판연구원장,석인선,헌법재판소-헌법재판연구원장-석인선,건물,배우자,아파트,...,0.0,0.0,0.0,"264,000.0",가액변동,2019,"(-126088.27272727272, 2302286.433992095]",1,서울,서대문구

In [98]:
seoul.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1754 entries, 47 to 43721
Data columns (total 23 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       1754 non-null   int64
 1   소속_대분류           1754 non-null   object
 2   소속_소분류           1754 non-null   object
 3   소속               1754 non-null   object
 4   직위               1732 non-null   object
 5   성명               1754 non-null   object
 6   개별index          1754 non-null   object
 7   대분류              1754 non-null   object
 8   본인과의 관계          1754 non-null   object
 9   재산의 종류           1754 non-null   object
 10  소재지 면적 등 권리의 명세  1754 non-null   object
 11  종전가액             1754 non-null   float64
 12  증가액              1754 non-null   float64
 13  증가액_실거래가         1754 non-null   float64
 14  감소액              1754 non-null   float64
 15  감소액_실거래가         1754 non-null   float64
 16  현재가액_x           1754 non-null   float64
 17  변동사유             1545 non-null   object
 18  years            1754 non-null   int64
 19  분위1              1753 non-null   category
 20  분위               1754 non-null   category
 21  광역시              1754 non-null   object
 22  자치구              1753 non-null   object
dtypes: category(2), float64(6), int64(2), object(13)
memory usage: 305.3+ KB

In [99]:
seoul['자치구'].unique()

array(['서초구', '양천구', '강서구', '중구', '관악구', '마포구', '노원구', '송파구', '강남구',
       '강남구개포동', '성북구', '서대문구', '한보미도맨션아파트건물128.01㎡(건물128.01㎡증가)', '은평구',
       '강동구', '용산구', '강남구논현동', '광진구', '성동구', '동작구', '강남구도곡동', '중랑구',
       '종로구', '개포1차지구아파트건물58.00㎡중29.00㎡', '동작구사당동', '영등포구',
       '오금쌍용스윗닷홈건물84.94㎡중', '구로구', '동대문구', '용산구서빙고동', '서초구방배동', '도봉구',
       '서초구우면동', '서초구서초동', '서초푸르지오써밋건물84.93㎡중', '강북구미아동', '잠원동',
       '래미안강동팰리스건물121.39㎡중60.69㎡', '강남구역삼동', '래미안강동팰리스건물84.97㎡중',
       '개포주공아파트(1단지)건물51.0', '금천구', '강북구', '목동신시가지아파트건물72.76㎡중36.38㎡',
       '거여동', '은마아파트건물0.00㎡(건물95.18㎡감소)', '은마아파트건물112.30㎡(건물112.30㎡증가)',
       '행당대림아파트건물11,544.12㎡중114.94㎡', '양천구신월동', '서초구반포동', '성동구금호동1가',
       '상왕십리동', '성동구행당동', '에이아이디차관주택건물72.51㎡중36.25㎡', nan,
       '중앙하이츠아파트건물84.97㎡(건물84.97㎡증가)', '대림아파트건물0.00㎡(건물84.91㎡감소)',
       '대림아파트건물84.91㎡(건물84.91㎡증가)', '흑석동', '건영3차아파트건물27,871.30㎡중84.82㎡',
       '삼익아파트건물151.54㎡(건물151.54㎡증가)', '삼익아파트', '신반포한신아파트건물116.00㎡중58.00㎡',
       '서초1차e-편한세상건물130.53㎡중65.26㎡', '대성유니드아파트건물120.73㎡중60.37㎡', '강동구고덕동',
       '개포1차지구아파트건물', '개포1차지구아파트건물41.98㎡중20.99㎡', '목동', '송파구가락동',
       '송파구방이2동', '건영아파트건물0.00㎡(건물84.51㎡감소)', '공덕동', '신성노바빌아파트건물59.78㎡중'],
      dtype=object)

In [116]:
seoul['자치구'].fillna('모름',inplace=True)

/Users/kang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py:6245: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._update_inplace(new_data)

In [141]:
seoul.loc[seoul['자치구'].str.contains('서초구',case=False),'자치구']='서초구'
seoul.loc[seoul['자치구'].str.contains('양천구',case=False),'자치구']='양천구'
seoul.loc[seoul['자치구'].str.contains('강서구',case=False),'자치구']='강서구'
seoul.loc[seoul['자치구'].str.contains('중구',case=False),'자치구']='중구'
seoul.loc[seoul['자치구'].str.contains('관악구',case=False),'자치구']='관악구'
seoul.loc[seoul['자치구'].str.contains('마포구',case=False),'자치구']='마포구'
seoul.loc[seoul['자치구'].str.contains('노원구',case=False),'자치구']='노원구'
seoul.loc[seoul['자치구'].str.contains('송파구',case=False),'자치구']='송파구'
seoul.loc[seoul['자치구'].str.contains('강남구',case=False),'자치구']='강남구'
seoul.loc[seoul['자치구'].str.contains('성북구',case=False),'자치구']='성북구'
seoul.loc[seoul['자치구'].str.contains('서대문구',case=False),'자치구']='서대문구'
seoul.loc[seoul['자치구'].str.contains('은평구',case=False),'자치구']='은평구'
seoul.loc[seoul['자치구'].str.contains('강동구',case=False),'자치구']='강동구'
seoul.loc[seoul['자치구'].str.contains('용산구',case=False),'자치구']='용산구'
seoul.loc[seoul['자치구'].str.contains('광진구',case=False),'자치구']='광진구'
seoul.loc[seoul['자치구'].str.contains('성동구',case=False),'자치구']='성동구'
seoul.loc[seoul['자치구'].str.contains('동작구',case=False),'자치구']='동작구'
seoul.loc[seoul['자치구'].str.contains('중랑구',case=False),'자치구']='중랑구'
seoul.loc[seoul['자치구'].str.contains('종로구',case=False),'자치구']='종로구'
seoul.loc[seoul['자치구'].str.contains('영등포구',case=False),'자치구']='영등포구'
seoul.loc[seoul['자치구'].str.contains('구로구',case=False),'자치구']='구로구'
seoul.loc[seoul['자치구'].str.contains('동대문구',case=False),'자치구']='동대문구'
seoul.loc[seoul['자치구'].str.contains('도봉구',case=False),'자치구']='도봉구'
seoul.loc[seoul['자치구'].str.contains('강북구',case=False),'자치구']='강북구'
seoul.loc[seoul['자치구'].str.contains('금천구',case=False),'자치구']='금천구'
seoul.loc[seoul['자치구'].str.contains('모름',case=False),'자치구']='기타'
seoul.loc[seoul['자치구'].str.contains('상왕십리동',case=False),'자치구']='기타'
seoul.loc[seoul['자치구'].str.contains('거여동',case=False),'자치구']='기타'
seoul.loc[seoul['자치구'].str.contains('삼익아파트',case=False),'자치구']='기타'
seoul.loc[seoul['자치구'].str.contains('목동',case=False),'자치구']='양천구'
seoul.loc[seoul['자치구'].str.contains('공덕동',case=False),'자치구']='마포구'
seoul.loc[seoul['자치구'].str.contains('잠원동',case=False),'자치구']='서초구'
seoul.loc[seoul['자치구'].str.contains('흑석동',case=False),'자치구']='동작구'

In [142]:
seoul.loc[seoul['자치구'].str.len()>5,'자치구']='기타'

In [143]:
seoul['자치구'].unique()

array(['서초구', '양천구', '강서구', '중구', '관악구', '마포구', '노원구', '송파구', '강남구',
       '성북구', '서대문구', '기타', '은평구', '강동구', '용산구', '광진구', '성동구', '동작구',
       '중랑구', '종로구', '영등포구', '구로구', '동대문구', '도봉구', '강북구', '금천구'],
      dtype=object)

In [ ]:
del